version: '3'
services:
  server:
    build: .
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
      - ./migrations:/usr/src/app/migrations
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: marusoftware/postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
volumes:
  postgres: