/* tslint:disable */
/* eslint-disable */
/**
 * ManabuAllergies API
 * API of ManabuAllergies
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const TokenType = {
    Bearer: 'bearer',
    Pre: 'pre'
} as const;
export type TokenType = typeof TokenType[keyof typeof TokenType];


export function TokenTypeFromJSON(json: any): TokenType {
    return TokenTypeFromJSONTyped(json, false);
}

export function TokenTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenType {
    return json as TokenType;
}

export function TokenTypeToJSON(value?: TokenType | null): any {
    return value as any;
}

